// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stok_Takip.Data;

#nullable disable

namespace Stok_Takip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517075115_paket37")]
    partial class paket37
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Stok_Takip.Models.Alis", b =>
                {
                    b.Property<int>("Alis_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Alis_Id"));

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Tedarikci_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Toplam_Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Alis_Id");

                    b.HasIndex("Tedarikci_Id");

                    b.ToTable("Alis");
                });

            modelBuilder.Entity("Stok_Takip.Models.AlisDetay", b =>
                {
                    b.Property<int>("AlisDetay_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlisDetay_Id"));

                    b.Property<int?>("Alis_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miktari")
                        .HasColumnType("int");

                    b.Property<int?>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("AlisDetay_Id");

                    b.HasIndex("Alis_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("AlisDetay");
                });

            modelBuilder.Entity("Stok_Takip.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Stok_Takip.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Stok_Takip.Models.Kategoriler", b =>
                {
                    b.Property<int>("Kategori_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kategori_Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori_Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kategori_Id");

                    b.ToTable("Kategorilers");
                });

            modelBuilder.Entity("Stok_Takip.Models.Musteriler", b =>
                {
                    b.Property<int>("Musteri_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Musteri_Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musteri_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Musteri_Id");

                    b.ToTable("Musterilers");
                });

            modelBuilder.Entity("Stok_Takip.Models.Resimler", b =>
                {
                    b.Property<int>("Resim_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Resim_Id"));

                    b.Property<string>("Resim_Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim_Yolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("Resim_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("Resimlers");
                });

            modelBuilder.Entity("Stok_Takip.Models.SatisDetay", b =>
                {
                    b.Property<int>("SatisDetay_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatisDetay_Id"));

                    b.Property<decimal?>("Birim_Fiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miktari")
                        .HasColumnType("int");

                    b.Property<int?>("Satis_Id")
                        .HasColumnType("int");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.Property<int?>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("SatisDetay_Id");

                    b.HasIndex("Satis_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("SatisDetay");
                });

            modelBuilder.Entity("Stok_Takip.Models.Satislar", b =>
                {
                    b.Property<int>("Satislar_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Satislar_Id"));

                    b.Property<int?>("Musteri_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Toplam_Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Satislar_Id");

                    b.HasIndex("Musteri_Id");

                    b.ToTable("SatisSatislar");
                });

            modelBuilder.Entity("Stok_Takip.Models.StokHareketleri", b =>
                {
                    b.Property<int>("Hareket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hareket_Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hareket_Turu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Miktari")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("Hareket_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("StokHareketleris");
                });

            modelBuilder.Entity("Stok_Takip.Models.Tedarikci", b =>
                {
                    b.Property<int>("Tedarikci_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tedarikci_Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkili_Kisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tedarikci_Id");

                    b.ToTable("Tedarikcis");
                });

            modelBuilder.Entity("Stok_Takip.Models.Urunler", b =>
                {
                    b.Property<int>("Urun_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Urun_Id"));

                    b.Property<decimal?>("Alis_Fiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kategori_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Minumum_Miktari")
                        .HasColumnType("int");

                    b.Property<decimal?>("Satis_Fiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stok_Miktari")
                        .HasColumnType("int");

                    b.Property<string>("Urun_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urun_Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Urun_Id");

                    b.HasIndex("Kategori_Id");

                    b.ToTable("Urunlers");
                });

            modelBuilder.Entity("Stok_Takip.Models.Yorumlar", b =>
                {
                    b.Property<int>("YorumlarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumlarId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urun_Id")
                        .HasColumnType("int");

                    b.Property<int?>("UrunlerUrun_Id")
                        .HasColumnType("int");

                    b.Property<string>("YorumYapan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YorumlarId");

                    b.HasIndex("UrunlerUrun_Id");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Stok_Takip.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Stok_Takip.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Stok_Takip.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Stok_Takip.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stok_Takip.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Stok_Takip.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stok_Takip.Models.Alis", b =>
                {
                    b.HasOne("Stok_Takip.Models.Tedarikci", "Tedarikci")
                        .WithMany("Alis")
                        .HasForeignKey("Tedarikci_Id");

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("Stok_Takip.Models.AlisDetay", b =>
                {
                    b.HasOne("Stok_Takip.Models.Alis", "Alis")
                        .WithMany("AlisDetays")
                        .HasForeignKey("Alis_Id");

                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("AlisDetays")
                        .HasForeignKey("Urun_Id");

                    b.Navigation("Alis");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Resimler", b =>
                {
                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("Resimlers")
                        .HasForeignKey("Urun_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.SatisDetay", b =>
                {
                    b.HasOne("Stok_Takip.Models.Satislar", "satislar")
                        .WithMany("SatisDetays")
                        .HasForeignKey("Satis_Id");

                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("SatisDetays")
                        .HasForeignKey("Urun_Id");

                    b.Navigation("Urunler");

                    b.Navigation("satislar");
                });

            modelBuilder.Entity("Stok_Takip.Models.Satislar", b =>
                {
                    b.HasOne("Stok_Takip.Models.Musteriler", "Musteriler")
                        .WithMany("Satislars")
                        .HasForeignKey("Musteri_Id");

                    b.Navigation("Musteriler");
                });

            modelBuilder.Entity("Stok_Takip.Models.StokHareketleri", b =>
                {
                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("StokHareketleris")
                        .HasForeignKey("Urun_Id");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Urunler", b =>
                {
                    b.HasOne("Stok_Takip.Models.Kategoriler", "kategoriler")
                        .WithMany("Urunler")
                        .HasForeignKey("Kategori_Id");

                    b.Navigation("kategoriler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Yorumlar", b =>
                {
                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("Yorumlars")
                        .HasForeignKey("UrunlerUrun_Id");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Alis", b =>
                {
                    b.Navigation("AlisDetays");
                });

            modelBuilder.Entity("Stok_Takip.Models.Kategoriler", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Musteriler", b =>
                {
                    b.Navigation("Satislars");
                });

            modelBuilder.Entity("Stok_Takip.Models.Satislar", b =>
                {
                    b.Navigation("SatisDetays");
                });

            modelBuilder.Entity("Stok_Takip.Models.Tedarikci", b =>
                {
                    b.Navigation("Alis");
                });

            modelBuilder.Entity("Stok_Takip.Models.Urunler", b =>
                {
                    b.Navigation("AlisDetays");

                    b.Navigation("Resimlers");

                    b.Navigation("SatisDetays");

                    b.Navigation("StokHareketleris");

                    b.Navigation("Yorumlars");
                });
#pragma warning restore 612, 618
        }
    }
}
