// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stok_Takip.Data;

#nullable disable

namespace Stok_Takip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stok_Takip.Models.Alis", b =>
                {
                    b.Property<int>("Alis_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Alis_Id"));

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Tedarikci_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Toplam_Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Alis_Id");

                    b.HasIndex("Tedarikci_Id");

                    b.ToTable("Alis");
                });

            modelBuilder.Entity("Stok_Takip.Models.AlisDetay", b =>
                {
                    b.Property<int>("AlisDetay_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlisDetay_Id"));

                    b.Property<int?>("Alis_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miktari")
                        .HasColumnType("int");

                    b.Property<int?>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("AlisDetay_Id");

                    b.HasIndex("Alis_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("AlisDetay");
                });

            modelBuilder.Entity("Stok_Takip.Models.Kategoriler", b =>
                {
                    b.Property<int>("Kategori_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kategori_Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori_Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kategori_Id");

                    b.ToTable("Kategorilers");
                });

            modelBuilder.Entity("Stok_Takip.Models.Musteriler", b =>
                {
                    b.Property<int>("Musteri_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Musteri_Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musteri_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Musteri_Id");

                    b.ToTable("Musterilers");
                });

            modelBuilder.Entity("Stok_Takip.Models.SatisDetay", b =>
                {
                    b.Property<int>("SatisDetay_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatisDetay_Id"));

                    b.Property<decimal?>("Birim_Fiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miktari")
                        .HasColumnType("int");

                    b.Property<int?>("Satis_Id")
                        .HasColumnType("int");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.Property<int?>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("SatisDetay_Id");

                    b.HasIndex("Satis_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("SatisDetay");
                });

            modelBuilder.Entity("Stok_Takip.Models.Satislar", b =>
                {
                    b.Property<int>("Satislar_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Satislar_Id"));

                    b.Property<int?>("Musteri_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Toplam_Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Satislar_Id");

                    b.HasIndex("Musteri_Id");

                    b.ToTable("SatisSatislar");
                });

            modelBuilder.Entity("Stok_Takip.Models.StokHareketleri", b =>
                {
                    b.Property<int>("Hareket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hareket_Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hareket_Turu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Miktari")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Urun_Id")
                        .HasColumnType("int");

                    b.HasKey("Hareket_Id");

                    b.HasIndex("Urun_Id");

                    b.ToTable("StokHareketleris");
                });

            modelBuilder.Entity("Stok_Takip.Models.Tedarikci", b =>
                {
                    b.Property<int>("Tedarikci_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tedarikci_Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkili_Kisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tedarikci_Id");

                    b.ToTable("Tedarikcis");
                });

            modelBuilder.Entity("Stok_Takip.Models.Urunler", b =>
                {
                    b.Property<int>("Urun_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Urun_Id"));

                    b.Property<decimal?>("Alis_Fiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kategori_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Minumum_Miktari")
                        .HasColumnType("int");

                    b.Property<decimal?>("Satis_Fiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stok_Miktari")
                        .HasColumnType("int");

                    b.Property<string>("Urun_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Urun_Id");

                    b.HasIndex("Kategori_Id");

                    b.ToTable("Urunlers");
                });

            modelBuilder.Entity("Stok_Takip.Models.Alis", b =>
                {
                    b.HasOne("Stok_Takip.Models.Tedarikci", "Tedarikci")
                        .WithMany("Alis")
                        .HasForeignKey("Tedarikci_Id");

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("Stok_Takip.Models.AlisDetay", b =>
                {
                    b.HasOne("Stok_Takip.Models.Alis", "Alis")
                        .WithMany("AlisDetays")
                        .HasForeignKey("Alis_Id");

                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("AlisDetays")
                        .HasForeignKey("Urun_Id");

                    b.Navigation("Alis");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.SatisDetay", b =>
                {
                    b.HasOne("Stok_Takip.Models.Satislar", "satislar")
                        .WithMany("SatisDetays")
                        .HasForeignKey("Satis_Id");

                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("SatisDetays")
                        .HasForeignKey("Urun_Id");

                    b.Navigation("Urunler");

                    b.Navigation("satislar");
                });

            modelBuilder.Entity("Stok_Takip.Models.Satislar", b =>
                {
                    b.HasOne("Stok_Takip.Models.Musteriler", "Musteriler")
                        .WithMany("Satislars")
                        .HasForeignKey("Musteri_Id");

                    b.Navigation("Musteriler");
                });

            modelBuilder.Entity("Stok_Takip.Models.StokHareketleri", b =>
                {
                    b.HasOne("Stok_Takip.Models.Urunler", "Urunler")
                        .WithMany("StokHareketleris")
                        .HasForeignKey("Urun_Id");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Urunler", b =>
                {
                    b.HasOne("Stok_Takip.Models.Kategoriler", "kategoriler")
                        .WithMany("Urunler")
                        .HasForeignKey("Kategori_Id");

                    b.Navigation("kategoriler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Alis", b =>
                {
                    b.Navigation("AlisDetays");
                });

            modelBuilder.Entity("Stok_Takip.Models.Kategoriler", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Stok_Takip.Models.Musteriler", b =>
                {
                    b.Navigation("Satislars");
                });

            modelBuilder.Entity("Stok_Takip.Models.Satislar", b =>
                {
                    b.Navigation("SatisDetays");
                });

            modelBuilder.Entity("Stok_Takip.Models.Tedarikci", b =>
                {
                    b.Navigation("Alis");
                });

            modelBuilder.Entity("Stok_Takip.Models.Urunler", b =>
                {
                    b.Navigation("AlisDetays");

                    b.Navigation("SatisDetays");

                    b.Navigation("StokHareketleris");
                });
#pragma warning restore 612, 618
        }
    }
}
